apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: '1234567890'
    jsonData:
      version: Flux
      organization: InfraMonitoring
      defaultBucket: InfraMonitoring
      tlsSkipVerify: true
